write-host "Show Variables"

write-host "Location - $Env:locationcode" 
write-host "appGatewaySubnet - $Env:appGatewaySubnet" 
write-host "billingStatus - $Env:billingStatus" 
write-host "costCenter - $Env:costCenter" 
write-host "SSRGName - $Env:SSRGName" 

write-host "Subnet SVNET - $Env:Subnet1SVNET" 
write-host "Subnet Firewall - $Env:Subnet2Firewall" 
write-host "Subnet MGMT - $Env:Subnet3MGMT" 
write-host "Subnet Services - $Env:Subnet4SS"
write-host "subnet App Gateway - $Env:Subnet5appGateway" 
write-host "subnet WZ - $Env:Subnet2WZ" 
write-host "Subnet1WZVNET - $Env:Subnet1WZVNET" 
write-host "WLRGName - $Env:WLRGName" 
write-host "AzureFirewallSubnet Name - $Env:AzureFirewallSubnetName"
write-host "Function Code - $Env:functionCode" 
write-host "Environment Code - $Env:environmentCode" 
write-host "Product Line Code - $Env:productLineCode" 
write-host "Customer Code - $Env:customerCode" 
write-host "App Gateway Name - $Env:roleCode"
write-host "App Gateway IP Address - $Env:privateIPAddress"
write-host "Workload IP Prefix - $Env:wladdressprefix"